version: '3.4'
services:
  web:
    image: nginx:1.13-alpine
    ports:
      - 8082:80
    volumes:
      - ./:/var/www/html
      - ./infra/nginx/fastrackOctobreBack.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    container_name: fastrackOctobreBack_web
  php:
    build:
      dockerfile: ./infra/php/Dockerfile
      context: .
    volumes:
      - ./:/var/www/html
      - ./infra/php/php.ini:/usr/local/etc/php/conf.d/default.ini
    container_name: fastrackOctobreBack_php
    links:
      - sql
  sql:
    image: mariadb:latest
    volumes:
      - ./infra/.mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: fastrackOctobreBack
      MYSQL_HOST: sql
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: fastrackOctobreBack
    ports:
      - 3308:3306
    container_name: fastrackOctobreBack_sql