api_login_check:
  path: /api/login


api_show_partner:
  path: /api/partner/{id}
  controller: App\Controller\PartnerController::show
  methods: GET
  requirements:
    id: '\d+'

api_list_partner:
  path: /api/partner/{options}/{order}
  controller: App\Controller\PartnerController::list
  methods: GET
  defaults:
    order: 'asc'
    options: null
  requirements:
    order: 'asc|desc|null'

api_delete_partner:
  path: /api/partner/{id}
  controller: App\Controller\PartnerController::delete
  methods: DELETE
  requirements:
    id: '\d+'

api_create_partner:
  path: /api/partner
  controller: App\Controller\PartnerController::create
  methods: POST

api_update_partner:
  path: /api/partner/{id}
  controller: App\Controller\PartnerController::update
  methods: PUT
  requirements:
    id: '\d+'

api_list_skill:
  path: /api/skill
  controller: App\Controller\SkillController::list
  methods: GET
