api_list_partner:
  path: /api/partner/{filter}
  controller: App\Controller\PartnerController::list
  methods: GET
  defaults:
    filter: null
  requirements:
    filter: 'asc|desc'

api_show_partner:
  path: /api/partner/{id}
  controller: App\Controller\PartnerController::show
  methods: GET
  requirements:
    id: '\d+'

api_delete_partner:
  path: /api/partner/{id}
  controller: App\Controller\PartnerController::delete
  methods: DELETE
  requirements:
    id: '\d+'

api_create_partner:
  path: /api/partner
  controller: App\Controller\PartnerController::create
  methods: POST