api_list_partner:
  path: /api/partner/list
  controller: App\Controller\PartnerController::List
  methods: GET

api_show_partner:
  path: /api/partner/{id}
  controller: App\Controller\PartnerController::show
  methods: GET
  requirements:
    id: '\d+'