api_list_partner:
  path: /api/partner/list
  controller: App\Controller\PartnerController::list
  methods: GET

api_show_partner:
  path: /api/partner/{id}
  controller: App\Controller\PartnerController::show
  methods: GET
  requirements:
    id: '\d+'

api_delete_partner:
  path: /api/partner/{id}
  controller: App\Controller\PartnerController::delete
  methods: DELETE
  requirements:
    id: '\d+'