<?php

namespace tests\Small\Entity;

use App\Entity\Partner;
use PHPUnit\Framework\TestCase;

class PartnerTest extends TestCase
{
    /** @var Partner */
    private $partner;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->partner = $this->init();
    }

    public function init(): Partner
    {
        return new Partner();
    }

    public function testSetAndGetFirstNameReturnValue()
    {
        $this->partner->setFirstName('Bob');
        $this->assertSame('Bob', $this->partner->getFirstName());
    }

    public function testGetFirstNameReturnNull()
    {
        $this->assertSame(null, $this->init()->getFirstName());
    }

    public function testSetAndGetLastNameReturnValue()
    {
        $this->partner->setLastName('Marley');
        $this->assertSame('Marley', $this->partner->getLastName());
    }

    public function testGetLastNameReturnNull()
    {
        $this->assertSame(null, $this->init()->getLastName());
    }

    public function testSetAndGetJobReturnValue()
    {
        $this->partner->setJob('Musicien');
        $this->assertSame('Musicien', $this->partner->getJob());
    }

    public function testGetJobReturnNull()
    {
        $this->assertSame(null, $this->init()->getJob());
    }

    public function testSetAndGetEmailReturnValue()
    {
        $this->partner->setEmail('bob.marley@link-value.fr');
        $this->assertSame('bob.marley@link-value.fr', $this->partner->getEmail());
    }

    public function testGetEmailReturnNull()
    {
        $this->assertSame(null, $this->init()->getEmail());
    }

    public function testSetAndGetPhoneNumberReturnValue()
    {
        $this->partner->setPhoneNumber('01 02 03 04 05');
        $this->assertSame('01 02 03 04 05', $this->partner->getPhoneNumber());
    }

    public function testGetPhoneNumberReturnNull()
    {
        $this->assertSame(null, $this->init()->getPhoneNumber());
    }

    public function testSetAndGetExperienceReturnValue()
    {
        $this->partner->setExperience(10);
        $this->assertSame(10, $this->partner->getExperience());
    }

    public function testGetExperienceReturnNull()
    {
        $this->assertSame(null, $this->init()->getExperience());
    }

    public function testGetCustomerReturnValue()
    {
        $this->partner->setCustomer('client');
        $this->assertSame('client', $this->partner->getCustomer());
    }

    public function testGetCustomerReturnNull()
    {
        $this->assertSame(null, $this->init()->getCustomer());
    }

    public function testSetAndGetProjectReturnValue()
    {
        $this->partner->setProject('booster');
        $this->assertSame('booster', $this->partner->getProject());
    }

    public function testGetProjectReturnNull()
    {
        $this->assertSame(null, $this->init()->getProject());
    }
}
