App\Entity\Category:
  type: entity
  table: category
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      lenght: 255
    parentId:
      type: integer
      nullable: true
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetimqe
      gedmo:
        timestampable:
          on: update
  manyToMany:
    skills:
      targetEntity: Skill
      joinTable:
        name: skills_categories
        joinColumns:
          category_id:
            referencedColumnName: id
        inverseJoinColumns:
          skill_id:
            referencedColumnName: id