App\Entity\Partner:
  type: entity
  table: partner
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    firstname:
      type: string
      lenght: 255
    lastname:
      type: string
      lenght: 255
    job:
      type: string
      lenght: 255
    email:
      type: string
      lenght: 50
      unique: true
    phone_number:
      type: string
      lenght: 30
    experience:
      type: integer
    customer:
      type: string
      lenght: 255
    project:
      type: string
      lenght: 255
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      gedmo:
        timestampable:
          on: update