App\Entity\Partner:
  type: entity
  table: partner
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    firstName:
      type: string
      lenght: 255
    lastName:
      type: string
      lenght: 255
    job:
      type: string
      lenght: 255
    email:
      type: string
      lenght: 50
    phoneNumber:
      type: string
      lenght: 30
    experience:
      type: integer
    customer:
      type: string
      lenght: 255
      nullable: true
    project:
      type: string
      lenght: 255
      nullable: true
    avatar:
      type: text
    favorites:
      type: array
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      gedmo:
        timestampable:
          on: update
    isActive:
      type: boolean
  oneToMany:
    skills:
      targetEntity: PartnerSkill
      mappedBy: partner