name: Git Checks

on: [push]

jobs:
  block-fixup:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - name: Block Fixup Commit Merge
        uses: 13rac1/block-fixup-merge-action@v1.0.0